### PR TITLE
Fix project setup

### LINKED ISSUE #25: Project's DB set-up
Maybe this is a silly issue, but I'm new to Docker and I got stuck setting up this project.

### Problem
Do I need anything more than what is in the original repo to run it?
For example:
 - Do I have to configure anything in *settings.py*? Like this:
```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'HOST': 'db',
        'PORT': 5432
    }
}
```
- Do I have to make any change in environmental variables? Especially in this part:
```
#env.local
DATABASE_URL=postgres://postgres@postgres:5432/db
```

- Do I have to add *POSTGRES_PASSWORD* or *POSTGRES_USER* to *docker-compose*?

### What I've tried
- Without any changes - `Error: Database is uninitialized and superuser password is not specified.`
- With *POSTGRES_PASSWORD* set in *docker-compose* I get this error:
image
But container seems to be working. When I try to make migration after that I get:
image

Maybe you know some quick-fix?

### PR DESCRIPTION
**Pull request by JSerwatka**
closes #25 

- settings.py: local database settings added
- docker-compose.yml:
	- web app waits for db to start and makes migations
	- db uses env vars from a file
- env-db-local: sets all settings that are needed for db container local setup
- README: additional required steps in _Project setup_ added

### CODE REVIEW

**Comment by mammuth** [comment]
Cool, thanks! 

I'll have to test whether this breaks usage with the divio CLI (especially the settings).

Alternatively we could also create a dedicated compose file.

**Comment by JSerwatka** [comment]
> I'll have to test whether this breaks usage with the divio CLI (especially the settings).

The db configuration in the settings works only in the debug mode, so there should be no issues there.
But you may want to check docker-compose. There is nothing fancy there, except forcing migrations after the db is ready and starting a server after that. However, I had to change the volume mounting on the db and move all env vars to a separate file, so make sure to adapt it to your needs.

**Comment by sheeshee** [comment]
Recently came across the project and would like to contribute, but I'm having trouble getting it to run locally. This PR gets it working, but I see that it wasn't merged. Just wondering why not and if there was a way we could include it in the main branch?

**Comment by mammuth** [comment]
I think I didn't merge it because when I tested it, it prevented some scripts from the Divio cli to work. 

Happy to see you contribute! Feel free to let me know what you're working on if you want some early help/input.

**Comment by sheeshee** [comment]
My intent is to help get the export function working eventually!

You say it prevented some Divio cli scripts to work. Can you say which ones so I can see if I get the same error? If you can also confirm what version of divio-cli you are running that would be helpful.

**Pull request closed without merging**
